# fly.toml app configuration file generated for purple-wind-9215 on 2023-06-14T09:49:17+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "purple-wind-9215"
primary_region = "arn"

[env]
  PORT = "8080" # add this

[http_service]
  internal_port = 8080 # default was 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"] # I added this, might not be needed?
